// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2024-2026 Maelstrom AI Pty Ltd ATF Maelstrom AI Holding Trust

//! Request types for hosted backend API endpoints.

use serde::{Deserialize, Serialize};
use serde_valid::Validate;

// Validation constants
//
// VA-HEP-003: Aligned to 2048 bytes. This is the practical upper bound for
// Origin header values and matches the value used by the challenge handler.
pub const MAX_ORIGIN_LENGTH: usize = 2048;
pub const MAX_PUBLIC_KEY_LENGTH: usize = 128;

/// Request to initiate a new hosted verification challenge.
///
/// This endpoint creates a PKCE flow, generates a provii-verifier challenge,
/// and returns session details to the frontend SDK.
///
/// For provii-agegate SDK compatibility, most fields are optional and will be
/// auto-generated or extracted from headers if not provided.
/// Accepts both camelCase (JS) and snake_case (Rust) field names.
///
/// # Authentication
///
/// Uses X-Public-Key header + Origin validation for authentication.
/// The public key identifies the relying party, and the origin is validated
/// against the allowed origins registered for that public key.
#[derive(Debug, Clone, Serialize, Deserialize, Validate)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ChallengeRequest {
    /// Public key identifier of the relying party (registered in KV)
    /// Can also be provided via X-Public-Key header
    #[serde(default, alias = "public_key")]
    #[validate(max_length = 128)]
    pub public_key: String,

    /// Origin (scheme + host + port) making the request
    /// Auto-extracted from Origin header if not provided
    #[serde(default)]
    #[validate(max_length = 256)]
    pub origin: String,

    /// PKCE code challenge (SHA-256 hash of code_verifier, base64url)
    /// Auto-generated by backend if not provided
    #[serde(default, alias = "code_challenge")]
    #[validate(max_length = 128)]
    pub code_challenge: String,

    /// PKCE code challenge method (must be "S256")
    /// Defaults to "S256" if not specified
    #[serde(
        default = "default_code_challenge_method",
        alias = "code_challenge_method"
    )]
    #[validate(custom(validate_code_challenge_method))]
    pub code_challenge_method: String,

    /// Environment for verification (production or sandbox)
    /// Defaults to "production" if not specified
    #[serde(default = "default_environment")]
    #[validate(custom(validate_environment))]
    pub environment: String,

    /// Optional metadata for analytics
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<ChallengeMetadata>,
}

fn default_code_challenge_method() -> String {
    "S256".to_string()
}

fn default_environment() -> String {
    "production".to_string()
}

/// Optional metadata for challenge requests.
#[derive(Debug, Clone, Serialize, Deserialize, Validate)]
#[serde(deny_unknown_fields)]
pub struct ChallengeMetadata {
    /// User agent string (max 500 chars)
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(max_length = 500)]
    pub user_agent: Option<String>,

    /// Client SDK version (max 50 chars)
    #[serde(skip_serializing_if = "Option::is_none")]
    #[validate(max_length = 50)]
    pub sdk_version: Option<String>,
}

// Validation functions

fn validate_code_challenge_method(method: &String) -> Result<(), serde_valid::validation::Error> {
    if method != "S256" {
        return Err(serde_valid::validation::Error::Custom(
            "code_challenge_method must be 'S256'".to_string(),
        ));
    }
    Ok(())
}

fn validate_environment(env: &String) -> Result<(), serde_valid::validation::Error> {
    if env != "production" && env != "sandbox" {
        return Err(serde_valid::validation::Error::Custom(
            "Environment must be 'production' or 'sandbox'".to_string(),
        ));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_challenge_request_valid() {
        let req = ChallengeRequest {
            public_key: "pk-test-123".to_string(),
            origin: "https://example.com".to_string(),
            code_challenge: "a".repeat(43),
            code_challenge_method: "S256".to_string(),
            environment: "production".to_string(),
            metadata: None,
        };
        assert!(req.validate().is_ok());
    }

    #[test]
    fn test_challenge_request_with_metadata() {
        let req = ChallengeRequest {
            public_key: "pk-test".to_string(),
            origin: "https://example.com".to_string(),
            code_challenge: "b".repeat(43),
            code_challenge_method: "S256".to_string(),
            environment: "production".to_string(),
            metadata: Some(ChallengeMetadata {
                user_agent: Some("Mozilla/5.0".to_string()),
                sdk_version: Some("1.0.0".to_string()),
            }),
        };
        assert!(req.validate().is_ok());
    }

    #[test]
    fn test_challenge_request_sandbox_environment() {
        let req = ChallengeRequest {
            public_key: "pk-test".to_string(),
            origin: "https://example.com".to_string(),
            code_challenge: "a".repeat(43),
            code_challenge_method: "S256".to_string(),
            environment: "sandbox".to_string(),
            metadata: None,
        };
        assert!(req.validate().is_ok());
    }

    #[test]
    fn test_challenge_request_invalid_environment() {
        let req = ChallengeRequest {
            public_key: "pk-test".to_string(),
            origin: "https://example.com".to_string(),
            code_challenge: "a".repeat(43),
            code_challenge_method: "S256".to_string(),
            environment: "invalid".to_string(),
            metadata: None,
        };
        assert!(req.validate().is_err());
    }
}
