// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2024-2026 Maelstrom AI Pty Ltd ATF Maelstrom AI Holding Trust

//! Sharding utilities for hosted Durable Objects
//!
//! Provides consistent hashing for distributing load across multiple DO instances.

/// Compute shard ID using seahash for consistent hashing.
///
/// SECURITY: Distributes DO load to prevent single-shard hot-spotting that
/// could be exploited for denial of service.
///
/// ADV-VA-035: SeaHash is not cryptographically secure (it is predictable given
/// known inputs), but the resource keys passed here are random UUIDs and nonces
/// generated by the server. An attacker cannot choose the shard key, so the
/// predictability of SeaHash does not enable targeted hot-spotting. If shard keys
/// ever include attacker-controlled input, this must be replaced with SipHash or
/// a keyed PRF.
pub fn compute_shard_id(key: &str, shard_count: usize) -> usize {
    let hash = seahash::hash(key.as_bytes());
    // Shard count is always small (< 100), so the modulo result fits in usize.
    let divisor = u64::try_from(shard_count).unwrap_or(1).max(1);
    let remainder = hash.checked_rem(divisor).unwrap_or(0);
    usize::try_from(remainder).unwrap_or(0)
}

/// Generate a shard name for a given key and shard count
pub fn get_shard_name(prefix: &str, key: &str, shard_count: usize) -> String {
    let shard_id = compute_shard_id(key, shard_count);
    format!("{}-shard-{}", prefix, shard_id)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_compute_shard_id_within_range() {
        let shard_count = 25;
        for i in 0..100 {
            let key = format!("test-key-{}", i);
            let shard_id = compute_shard_id(&key, shard_count);
            assert!(shard_id < shard_count, "Shard ID {} out of range", shard_id);
        }
    }

    #[test]
    fn test_compute_shard_id_deterministic() {
        let key = "test-key-123";
        let shard_count = 25;
        let shard1 = compute_shard_id(key, shard_count);
        let shard2 = compute_shard_id(key, shard_count);
        assert_eq!(shard1, shard2, "Shard IDs should be deterministic");
    }

    #[test]
    fn test_get_shard_name_format_hosted_session() {
        let shard_name = get_shard_name("hosted-session", "test-key", 25);
        assert!(shard_name.starts_with("hosted-session-shard-"));
        assert!(shard_name.ends_with(|c: char| c.is_ascii_digit()));
    }

    #[test]
    fn test_get_shard_name_format_hosted_nonce() {
        let shard_name = get_shard_name("hosted-nonce", "test-key", 25);
        assert!(shard_name.starts_with("hosted-nonce-shard-"));
        assert!(shard_name.ends_with(|c: char| c.is_ascii_digit()));
    }

    #[test]
    fn test_different_keys_distributed() {
        let shard_count = 10;
        let mut shard_counts: Vec<u32> = vec![0; shard_count];

        // Generate 1000 keys and count distribution
        for i in 0..1000 {
            let key = format!("key-{}", i);
            let shard_id = compute_shard_id(&key, shard_count);
            if let Some(c) = shard_counts.get_mut(shard_id) {
                *c = c.saturating_add(1);
            }
        }

        // Each shard should have at least some keys (basic distribution check)
        for count in &shard_counts {
            assert!(*count > 0, "Shard should receive at least some keys");
        }
    }

    #[test]
    fn test_single_shard() {
        let key = "test-key";
        let shard_id = compute_shard_id(key, 1);
        assert_eq!(shard_id, 0);
    }
}
